// Embeds the few images used as 3D textures, so WebGL works even from file://
import { readFileSync, writeFileSync } from 'node:fs';
const files = ['biohazard-label', 'itec-logo', 'iso-badges', 'trend-logo', 'trend-e'];
const out = files.map(f => `  'assets/${f}.png': 'data:image/jpeg;base64,${readFileSync(`tex/${f}.jpg`).toString('base64')}'`).join(',\n');
writeFileSync('../js/src/textures.js', `// generated by tools/build.sh — do not edit\nexport default {\n${out}\n};\n`);
